version: '3.3'

services:
  firefly_iii:
    image: jc5x/firefly-iii:latest
    volumes:
      - firefly_iii_export:/var/www/firefly-iii/storage/export
      - firefly_iii_upload:/var/www/firefly-iii/storage/upload
    env_file: .env
    ports:
      - 8080:80
    depends_on:
      - firefly_iii_db
  
  firefly_iii_db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD=secret_firefly_password
    volumes:
      - firefly_iii_db:/var/lib/postgresql/data

volumes:
   firefly_iii_export:
   firefly_iii_upload:
   firefly_iii_db:
